TEMPLATE = app
QT = gui core phonon sql
CONFIG += qt warn_on release
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ui/player.ui
HEADERS = src/player.h src/database.h
SOURCES = src/player.cpp src/main.cpp src/database.cpp
